geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('activate/<str:pk>/', authapp.activate, name="activate")
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from authapp import urls as authapp_urls
from mainapp import urls as mainapp_urls
from adminapp import urls as adminapp_urls
from basketapp import urls as basketapp_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),

    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(mainapp_urls, namespace='products'), name='products'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),

    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/authapp/models.py
import hashlib
import random
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class User(AbstractUser):
    avatar = models.ImageField(upload_to='user_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст', default=18)

    is_delete = models.BooleanField(default=False)

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(blank=True)

    activated = models.BooleanField('Активирован ли аккаунт', default=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            # not created now
            self.activated = False
            salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]

            self.activation_key = hashlib.sha1((self.email + salt).encode('utf8')).hexdigest()
            self.activation_key_expires = now() + timedelta(hours=48)
            
            # send activated email
            send_mail(
                'Email from django',
                f"""
                Активируйте свой аккаунт
                http://127.0.0.1:8000/auth/activate/{self.activation_key}/
                """,
                settings.EMAIL_HOST_USER,
                [self.email],
                fail_silently=False
            )
        super().save(*args, **kwargs)


    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        else:
            return True


class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'М'),
        ('W', 'Ж'),
    )

    user = models.OneToOneField(User, unique=True, null=False,\
                                db_index=True, on_delete=models.CASCADE)
    tagline = models.CharField(verbose_name='теги', max_length=128, \
                               blank=True)
    about_me = models.TextField(verbose_name='о себе', max_length=512, \
                               blank=True)
    gender = models.CharField(verbose_name='пол', max_length=1, \
                              choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from .models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('tagline', 'about_me', 'gender')


    def __init__(self, *args, **kwargs):
        super(UserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/authapp/views.py
import re
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import auth
from django.urls import reverse
from authapp.models import User
from django.contrib import messages
from django.db import transaction

from authapp.forms import UserLoginForm, UserRegisterForm, UserEditForm, UserProfileEditForm


def login(request):
    title = 'входа'

    login_form = UserLoginForm(data=request.POST)
    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        passsword = request.POST['password']

        user = auth.authenticate(username=username, password=passsword)
        if user.activated:
            auth.authenticate()
            if user and user.is_active:
                auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                if 'next' in request.POST.keys():
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('index'))
        messages.error(request, 'Аккаунт не активирован')

    context = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            messages.success(request, "E-mail с подтверждением отправлен на Вашу элетронную почту")
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = UserRegisterForm()

    context = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', context)


@transaction.atomic
def edit(request):
    title = 'редактирование'
    
    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, request.FILES, \
                                     instance=request.user)
        profile_form = UserProfileEditForm(request.POST, \
                                     instance=request.user.userprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = UserEditForm(instance=request.user)
        profile_form = UserProfileEditForm(
            instance=request.user.userprofile
        )
    
    content = {
        'title': title, 
        'edit_form': edit_form, 
        'profile_form': profile_form
    }
    
    return render(request, 'authapp/edit.html', content)


def activate(request, pk):
    user = User.objects.filter(activation_key=pk).first()
    if not user:
        return redirect('/404')
    if not user.is_activation_key_expired():
        user.activated = True
        user.save()
        return render(request, 'authapp/success_activate.html')
    return render(request, 'authapp/key_expired.html')

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'authapp/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
	<div class="container_wrapper">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="col-4 mx-auto">
        <div class="row">
            <div class="user_avatar">
                <img src="/media/{{ user.avatar }}" class="rounded-circle">
            </div>
        </div>
    <div class="row">
        <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            {{ profile_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'index' %}" class="">
                на главную
            </a>
        </button>
    </div>
    </div>
{% endblock %}

geekshop/authapp/templates/authapp/key_expired.html
<h1>Данный ключ просрочен, <a href="/auth/register/">зарегистрируйтесь</a>заново</h1>

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
  <div class="login_container">
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
      {% csrf_token %}
      {{ login_form.as_p }}

      <br>
      {% if next %}
          <input type="hidden" name="next" value="{{ next }}">
      {% endif %}
      <input class="form-control btn btn-primary" type="submit" value="войти">
    </form>

    <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            зарегистрироваться
        </a>
    </button>
    <button class="btn btn-round form-control">
      <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
       Вход через ВКонтакте 
      </a>
    </button>
  </div>


{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
    </div>

{% endblock %}

geekshop/authapp/templates/authapp/success_activate.html
<h1>Ваш аккаунт успешно активирован</h1>
<a href="/auth/login/">Войти</a>